/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        display: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        // token aliases (in case Stitch HTML uses these)
        'display-xl': ['Newsreader', 'serif'],
        'display-lg': ['Newsreader', 'serif'],
        'headline-lg': ['Newsreader', 'serif'],
        'headline-md': ['Newsreader', 'serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl':  ['6rem',     { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '400' }],
        'display-lg':  ['3.75rem',  { lineHeight: '1.1',  letterSpacing: '-0.025em', fontWeight: '400' }],
        'headline-lg': ['2.25rem',  { lineHeight: '1.2',  letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-md': ['1.5rem',   { lineHeight: '1.3',  letterSpacing: '-0.01em',  fontWeight: '500' }],
        'title-sm':    ['0.75rem',  { lineHeight: '1.5',  letterSpacing: '0.18em',   fontWeight: '500' }],
        'body-lg':     ['1.125rem', { lineHeight: '1.7',  letterSpacing: '0',        fontWeight: '400' }],
        'body-md':     ['1rem',     { lineHeight: '1.6',  letterSpacing: '0',        fontWeight: '400' }],
        'label-caps':  ['0.75rem',  { lineHeight: '1',    letterSpacing: '0.1em',    fontWeight: '500' }],
      },
      colors: {
        // Editorial palette
        cream:      '#FBF8F3',
        oat:        '#F5EFE6',
        linen:      '#EDE6D9',
        espresso:   '#1F1A14',
        cocoa:      '#3D2E20',
        copper:     '#A8763E',
        'copper-soft': '#C49968',
        sage:       '#7C8C6B',
        tomato:     '#C0593E',
        // Stitch token aliases
        surface:        '#FBF8F3',
        'on-surface':   '#1F1A14',
        primary:        '#A8763E',
        'on-primary':   '#FBF8F3',
        secondary:      '#3D2E20',
        'on-secondary': '#FBF8F3',
        'inverse-surface': '#1F1A14',
        'inverse-on-surface': '#FBF8F3',
        outline:        '#3D2E20',
        'outline-variant': '#D8CFBE',
        background:     '#FBF8F3',
        'on-background': '#1F1A14',
      },
      spacing: {
        gutter: '2rem',
        'grid-gutter': '4rem',
        'element-gap': '2.5rem',
        'section-padding-y': '6rem',
        'margin-inline': '2rem',
        'stack-xs': '0.5rem',
        'stack-sm': '1rem',
        'stack-md': '1.5rem',
        'stack-lg': '3rem',
        'stack-xl': '5rem',
      },
      maxWidth: {
        'container-max': '88rem',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        DEFAULT_LG: '0.25rem',
        lg: '0.25rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
